# Generated by Django 5.2.11 on 2026-03-04 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('short', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True, verbose_name='Короткая ссылка')),
                ('original', models.TextField(null=True, verbose_name='Оригинальная ссылка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'links',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('browser', models.TextField(null=True, verbose_name='Браузер запрашивающего')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время обращения')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='links.link')),
            ],
            options={
                'db_table': 'visits',
            },
        ),
    ]
