# Generated by Django 5.2.11 on 2026-03-04 16:07

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_trigram_extension'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['original'], name='link_original_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=django.contrib.postgres.indexes.GinIndex(fields=['original'], name='link_original_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
